package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbCanchas generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbCanchas implements java.io.Serializable {

	private int idcancha;
	private TbTipoEscenario tbTipoEscenario;
	private TbTiposDeporte tbTiposDeporte;
	private String nombre;

	public TbCanchas() {
	}

	public TbCanchas(int idcancha) {
		this.idcancha = idcancha;
	}

	public TbCanchas(int idcancha, TbTipoEscenario tbTipoEscenario, TbTiposDeporte tbTiposDeporte, String nombre) {
		this.idcancha = idcancha;
		this.tbTipoEscenario = tbTipoEscenario;
		this.tbTiposDeporte = tbTiposDeporte;
		this.nombre = nombre;
	}

	public int getIdcancha() {
		return this.idcancha;
	}

	public void setIdcancha(int idcancha) {
		this.idcancha = idcancha;
	}

	public TbTipoEscenario getTbTipoEscenario() {
		return this.tbTipoEscenario;
	}

	public void setTbTipoEscenario(TbTipoEscenario tbTipoEscenario) {
		this.tbTipoEscenario = tbTipoEscenario;
	}

	public TbTiposDeporte getTbTiposDeporte() {
		return this.tbTiposDeporte;
	}

	public void setTbTiposDeporte(TbTiposDeporte tbTiposDeporte) {
		this.tbTiposDeporte = tbTiposDeporte;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}
