package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbCanchasxunidadDeportiva generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbCanchasxunidadDeportiva implements java.io.Serializable {

	private int idcanchaUnidad;
	private TbCanchas tbCanchas;
	private TbUnidadesDeportivas tbUnidadesDeportivas;
	private String nombre;
	private Date disponibleInicio;
	private Date disponibleFin;
	private TbEstados tbEstados;
	
	private String mensajeError;
	
	
	public TbCanchasxunidadDeportiva() {
	}

	public TbCanchasxunidadDeportiva(int idcanchaUnidad) {
		this.idcanchaUnidad = idcanchaUnidad;
	}

	public TbCanchasxunidadDeportiva(String mensajeError) {
		super();
		this.mensajeError = mensajeError;
	}

	public int getIdcanchaUnidad() {
		return idcanchaUnidad;
	}

	public void setIdcanchaUnidad(int idcanchaUnidad) {
		this.idcanchaUnidad = idcanchaUnidad;
	}

	public TbCanchas getTbCanchas() {
		return tbCanchas;
	}

	public void setTbCanchas(TbCanchas tbCanchas) {
		this.tbCanchas = tbCanchas;
	}

	public TbUnidadesDeportivas getTbUnidadesDeportivas() {
		return tbUnidadesDeportivas;
	}

	public void setTbUnidadesDeportivas(TbUnidadesDeportivas tbUnidadesDeportivas) {
		this.tbUnidadesDeportivas = tbUnidadesDeportivas;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getDisponibleInicio() {
		return disponibleInicio;
	}

	public void setDisponibleInicio(Date disponibleInicio) {
		this.disponibleInicio = disponibleInicio;
	}

	public Date getDisponibleFin() {
		return disponibleFin;
	}

	public void setDisponibleFin(Date disponibleFin) {
		this.disponibleFin = disponibleFin;
	}

	public TbEstados getTbEstados() {
		return tbEstados;
	}

	public void setTbEstados(TbEstados tbEstados) {
		this.tbEstados = tbEstados;
	}

	public String getMensajeError() {
		return mensajeError;
	}

	public void setMensajeError(String mensajeError) {
		this.mensajeError = mensajeError;
	}	
}
