package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbCanchasxunidadDeportiva generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbCanchasxunidadDeportiva implements java.io.Serializable {

	private int idcanchaUnidad;
	private TbCanchas tbCanchas;
	private TbUnidadesDeportivas tbUnidadesDeportivas;
	private String nombre;
	private Date disponibleInicio;
	private Date disponibleFin;
	private Boolean estado;
	
	public TbCanchasxunidadDeportiva() {
	}

	public TbCanchasxunidadDeportiva(int idcanchaUnidad) {
		this.idcanchaUnidad = idcanchaUnidad;
	}

	public TbCanchasxunidadDeportiva(int idcanchaUnidad, TbCanchas tbCanchas, TbUnidadesDeportivas tbUnidadesDeportivas,
			String nombre, Date disponibleInicio, Date disponibleFin, Boolean estado) {
		this.idcanchaUnidad = idcanchaUnidad;
		this.tbCanchas = tbCanchas;
		this.tbUnidadesDeportivas = tbUnidadesDeportivas;
		this.nombre = nombre;
		this.disponibleInicio = disponibleInicio;
		this.disponibleFin = disponibleFin;
		this.estado = estado;
	}

	public int getIdcanchaUnidad() {
		return this.idcanchaUnidad;
	}

	public void setIdcanchaUnidad(int idcanchaUnidad) {
		this.idcanchaUnidad = idcanchaUnidad;
	}

	public TbCanchas getTbCanchas() {
		return this.tbCanchas;
	}

	public void setTbCanchas(TbCanchas tbCanchas) {
		this.tbCanchas = tbCanchas;
	}

	public TbUnidadesDeportivas getTbUnidadesDeportivas() {
		return this.tbUnidadesDeportivas;
	}

	public void setTbUnidadesDeportivas(TbUnidadesDeportivas tbUnidadesDeportivas) {
		this.tbUnidadesDeportivas = tbUnidadesDeportivas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getDisponibleInicio() {
		return this.disponibleInicio;
	}

	public void setDisponibleInicio(Date disponibleInicio) {
		this.disponibleInicio = disponibleInicio;
	}

	public Date getDisponibleFin() {
		return this.disponibleFin;
	}

	public void setDisponibleFin(Date disponibleFin) {
		this.disponibleFin = disponibleFin;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
