package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbCiudades generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbCiudades implements java.io.Serializable {

	private int idciudad;
	private TbDepartamentos tbDepartamentos;
	private String nombre;

	public TbCiudades() {
	}

	public TbCiudades(int idciudad) {
		this.idciudad = idciudad;
	}

	public TbCiudades(int idciudad, TbDepartamentos tbDepartamentos, String nombre) {
		this.idciudad = idciudad;
		this.tbDepartamentos = tbDepartamentos;
		this.nombre = nombre;
	}

	public int getIdciudad() {
		return this.idciudad;
	}

	public void setIdciudad(int idciudad) {
		this.idciudad = idciudad;
	}

	public TbDepartamentos getTbDepartamentos() {
		return this.tbDepartamentos;
	}

	public void setTbDepartamentos(TbDepartamentos tbDepartamentos) {
		this.tbDepartamentos = tbDepartamentos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}
