package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbDepartamentos generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbDepartamentos implements java.io.Serializable {

	private int iddepartamento;
	private String nombre;

	public TbDepartamentos() {
	}

	public int getIddepartamento() {
		return this.iddepartamento;
	}

	public void setIddepartamento(int iddepartamento) {
		this.iddepartamento = iddepartamento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
