package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbEstados generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbEstados implements java.io.Serializable {

	private int idestado;
	private String tablaReferencia;
	private String valor;

	public TbEstados() {
	}

	public TbEstados(int idestado) {
		this.idestado = idestado;
	}

	public TbEstados(int idestado, String tablaReferencia, String valor) {
		this.idestado = idestado;
		this.tablaReferencia = tablaReferencia;
		this.valor = valor;
	}

	/**
	 * @return the idestado
	 */
	public int getIdestado() {
		return idestado;
	}

	/**
	 * @param idestado the idestado to set
	 */
	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	/**
	 * @return the tablaReferencia
	 */
	public String getTablaReferencia() {
		return tablaReferencia;
	}

	/**
	 * @param tablaReferencia the tablaReferencia to set
	 */
	public void setTablaReferencia(String tablaReferencia) {
		this.tablaReferencia = tablaReferencia;
	}

	/**
	 * @return the valor
	 */
	public String getValor() {
		return valor;
	}

	/**
	 * @param valor the valor to set
	 */
	public void setValor(String valor) {
		this.valor = valor;
	}
}
