package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbLocalidades generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbLocalidades implements java.io.Serializable {

	private int idlocalidad;
	private TbCiudades tbCiudades;
	private String nombre;

	private String mensajeError;

	/**
	 * Constructor
	 */
	public TbLocalidades() {
		super();
	}

	/**
	 * @param idlocalidad
	 * @param tbCiudades
	 * @param nombre
	 */
	public TbLocalidades(int idlocalidad, TbCiudades tbCiudades, String nombre) {
		super();
		this.idlocalidad = idlocalidad;
		this.tbCiudades = tbCiudades;
		this.nombre = nombre;
	}

	/**
	 * @return the idlocalidad
	 */
	public int getIdlocalidad() {
		return idlocalidad;
	}

	/**
	 * @param idlocalidad the idlocalidad to set
	 */
	public void setIdlocalidad(int idlocalidad) {
		this.idlocalidad = idlocalidad;
	}

	/**
	 * @return the tbCiudades
	 */
	public TbCiudades getTbCiudades() {
		return tbCiudades;
	}

	/**
	 * @param tbCiudades the tbCiudades to set
	 */
	public void setTbCiudades(TbCiudades tbCiudades) {
		this.tbCiudades = tbCiudades;
	}

	/**
	 * @return the nombre
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * @param nombre the nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * @return the mensajeError
	 */
	public String getMensajeError() {
		return mensajeError;
	}

	/**
	 * @param mensajeError the mensajeError to set
	 */
	public void setMensajeError(String mensajeError) {
		this.mensajeError = mensajeError;
	}

}
