package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbLocalidades generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbLocalidades implements java.io.Serializable {

	private int idlocalidad;
	private TbCiudades tbCiudades;
	private String nombre;

	public TbLocalidades() {
	}

	public TbLocalidades(int idlocalidad) {
		this.idlocalidad = idlocalidad;
	}

	public TbLocalidades(int idlocalidad, TbCiudades tbCiudades, String nombre) {
		this.idlocalidad = idlocalidad;
		this.tbCiudades = tbCiudades;
		this.nombre = nombre;
	}

	public int getIdlocalidad() {
		return this.idlocalidad;
	}

	public void setIdlocalidad(int idlocalidad) {
		this.idlocalidad = idlocalidad;
	}

	public TbCiudades getTbCiudades() {
		return this.tbCiudades;
	}

	public void setTbCiudades(TbCiudades tbCiudades) {
		this.tbCiudades = tbCiudades;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
