package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbPagos generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbPagos implements java.io.Serializable {

	private int idpago;
	private TbReservas tbReservas;
	private Date fechaPago;
	private BigDecimal valorPago;
	private String observacion;

	public TbPagos() {
	}

	public TbPagos(int idpago) {
		this.idpago = idpago;
	}

	public TbPagos(int idpago, TbReservas tbReservas, Date fechaPago, BigDecimal valorPago, String observacion) {
		this.idpago = idpago;
		this.tbReservas = tbReservas;
		this.fechaPago = fechaPago;
		this.valorPago = valorPago;
		this.observacion = observacion;
	}

	public int getIdpago() {
		return this.idpago;
	}

	public void setIdpago(int idpago) {
		this.idpago = idpago;
	}

	public TbReservas getTbReservas() {
		return this.tbReservas;
	}

	public void setTbReservas(TbReservas tbReservas) {
		this.tbReservas = tbReservas;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public BigDecimal getValorPago() {
		return this.valorPago;
	}

	public void setValorPago(BigDecimal valorPago) {
		this.valorPago = valorPago;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
