package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbPagos generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbPagos implements java.io.Serializable {

	private int idpago;
	private TbReservas tbReservas;
	private Date fechaPago;
	private BigDecimal valorPago;
	private String observacion;
	

	/**
	 * Constructor
	 */
	public TbPagos() {
		super();
	}

	/**
	 * @param idpago
	 * @param tbReservas
	 * @param fechaPago
	 * @param valorPago
	 */
	public TbPagos(int idpago, TbReservas tbReservas, Date fechaPago, BigDecimal valorPago) {
		super();
		this.idpago = idpago;
		this.tbReservas = tbReservas;
		this.fechaPago = fechaPago;
		this.valorPago = valorPago;
	}

	/**
	 * @return the idpago
	 */
	public int getIdpago() {
		return idpago;
	}

	/**
	 * @param idpago the idpago to set
	 */
	public void setIdpago(int idpago) {
		this.idpago = idpago;
	}

	/**
	 * @return the tbReservas
	 */
	public TbReservas getTbReservas() {
		return tbReservas;
	}

	/**
	 * @param tbReservas the tbReservas to set
	 */
	public void setTbReservas(TbReservas tbReservas) {
		this.tbReservas = tbReservas;
	}

	/**
	 * @return the fechaPago
	 */
	public Date getFechaPago() {
		return fechaPago;
	}

	/**
	 * @param fechaPago the fechaPago to set
	 */
	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	/**
	 * @return the valorPago
	 */
	public BigDecimal getValorPago() {
		return valorPago;
	}

	/**
	 * @param valorPago the valorPago to set
	 */
	public void setValorPago(BigDecimal valorPago) {
		this.valorPago = valorPago;
	}

	/**
	 * @return the observacion
	 */
	public String getObservacion() {
		return observacion;
	}

	/**
	 * @param observacion the observacion to set
	 */
	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	
}
