package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbPersonas generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbPersonas implements java.io.Serializable {

	private int idpersona;
	private TbCiudades tbCiudades;
	private TbTiposDocumento tbTiposDocumento;
	private String nombres;
	private String apellidos;
	private String direccion;
	private String telefonoFijo;
	private String telefonoCelular;
	private String email;
	private String numeroDocumento;

	public TbPersonas() {
	}

	public TbPersonas(int idpersona) {
		this.idpersona = idpersona;
	}

	public TbPersonas(int idpersona, TbCiudades tbCiudades, TbTiposDocumento tbTiposDocumento, String nombres,
			String apellidos, String direccion, String telefonoFijo, String telefonoCelular, String email,
			String numeroDocumento) {
		this.idpersona = idpersona;
		this.tbCiudades = tbCiudades;
		this.tbTiposDocumento = tbTiposDocumento;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.telefonoFijo = telefonoFijo;
		this.telefonoCelular = telefonoCelular;
		this.email = email;
		this.numeroDocumento = numeroDocumento;
	}

	public int getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(int idpersona) {
		this.idpersona = idpersona;
	}

	public TbCiudades getTbCiudades() {
		return this.tbCiudades;
	}

	public void setTbCiudades(TbCiudades tbCiudades) {
		this.tbCiudades = tbCiudades;
	}

	public TbTiposDocumento getTbTiposDocumento() {
		return this.tbTiposDocumento;
	}

	public void setTbTiposDocumento(TbTiposDocumento tbTiposDocumento) {
		this.tbTiposDocumento = tbTiposDocumento;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefonoFijo() {
		return this.telefonoFijo;
	}

	public void setTelefonoFijo(String telefonoFijo) {
		this.telefonoFijo = telefonoFijo;
	}

	public String getTelefonoCelular() {
		return this.telefonoCelular;
	}

	public void setTelefonoCelular(String telefonoCelular) {
		this.telefonoCelular = telefonoCelular;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}
}
