package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbPersonaRol generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbPersonaRol implements java.io.Serializable {

	private int idpersonaRol;
	private String descripcion;
	private String persona;
	private String rol;
	private String estado;

	

	/**
	 * Constructor
	 */
	public TbPersonaRol() {
		super();
	}
	
	/**
	 * @param idpersonaRol
	 * @param descripcion
	 * @param persona
	 * @param rol
	 */
	public TbPersonaRol(int idpersonaRol, String descripcion, String persona, String rol) {
		super();
		this.idpersonaRol = idpersonaRol;
		this.descripcion = descripcion;
		this.persona = persona;
		this.rol = rol;
	}
	
	/**
	 * @return the idpersonaRol
	 */
	public int getIdpersonaRol() {
		return idpersonaRol;
	}



	/**
	 * @param idpersonaRol the idpersonaRol to set
	 */
	public void setIdpersonaRol(int idpersonaRol) {
		this.idpersonaRol = idpersonaRol;
	}

	/**
	 * @return the descripcion
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * @param descripcion the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * @return the persona
	 */
	public String getPersona() {
		return persona;
	}

	/**
	 * @param persona the persona to set
	 */
	public void setPersona(String persona) {
		this.persona = persona;
	}

	/**
	 * @return the rol
	 */
	public String getRol() {
		return rol;
	}

	/**
	 * @param rol the rol to set
	 */
	public void setRol(String rol) {
		this.rol = rol;
	}

	/**
	 * @return the estado
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * @param estado the estado to set
	 */
	public void setEstado(String estado) {
		this.estado = estado;
	}

}
