package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbPersonaRol generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbPersonaRol implements java.io.Serializable {

	private int idpersonaRol;
	private String descripcion;
	private String persona;
	private String rol;
	private String estado;

	public TbPersonaRol() {
	}

	public TbPersonaRol(int idpersonaRol) {
		this.idpersonaRol = idpersonaRol;
	}

	public TbPersonaRol(int idpersonaRol, String descripcion, String persona, String rol, String estado) {
		this.idpersonaRol = idpersonaRol;
		this.descripcion = descripcion;
		this.persona = persona;
		this.rol = rol;
		this.estado = estado;
	}

	public int getIdpersonaRol() {
		return this.idpersonaRol;
	}

	public void setIdpersonaRol(int idpersonaRol) {
		this.idpersonaRol = idpersonaRol;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getPersona() {
		return this.persona;
	}

	public void setPersona(String persona) {
		this.persona = persona;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
