package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbPersonas generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbPersonas implements java.io.Serializable {

	private int idpersona;
	private TbCiudades tbCiudades;
	private TbTiposDocumento tbTiposDocumento;
	private String nombres;
	private String apellidos;
	private String direccion;
	private String telefonoFijo;
	private String telefonoCelular;
	private String email;
	private String numeroDocumento;
	
	private String mensajeError;

	
	/**
	 * 
	 */
	public TbPersonas() {
		super();
	}

	/**
	 * @param idpersona
	 * @param tbCiudades
	 * @param tbTiposDocumento
	 * @param nombres
	 * @param apellidos
	 * @param numeroDocumento
	 */
	public TbPersonas(int idpersona, TbCiudades tbCiudades, TbTiposDocumento tbTiposDocumento, String nombres,
			String apellidos, String numeroDocumento) {
		super();
		this.idpersona = idpersona;
		this.tbCiudades = tbCiudades;
		this.tbTiposDocumento = tbTiposDocumento;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.numeroDocumento = numeroDocumento;
	}

	/**
	 * @return the idpersona
	 */
	public int getIdpersona() {
		return idpersona;
	}

	/**
	 * @param idpersona the idpersona to set
	 */
	public void setIdpersona(int idpersona) {
		this.idpersona = idpersona;
	}

	/**
	 * @return the tbCiudades
	 */
	public TbCiudades getTbCiudades() {
		return tbCiudades;
	}

	/**
	 * @param tbCiudades the tbCiudades to set
	 */
	public void setTbCiudades(TbCiudades tbCiudades) {
		this.tbCiudades = tbCiudades;
	}

	/**
	 * @return the tbTiposDocumento
	 */
	public TbTiposDocumento getTbTiposDocumento() {
		return tbTiposDocumento;
	}

	/**
	 * @param tbTiposDocumento the tbTiposDocumento to set
	 */
	public void setTbTiposDocumento(TbTiposDocumento tbTiposDocumento) {
		this.tbTiposDocumento = tbTiposDocumento;
	}

	/**
	 * @return the nombres
	 */
	public String getNombres() {
		return nombres;
	}

	/**
	 * @param nombres the nombres to set
	 */
	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	/**
	 * @return the apellidos
	 */
	public String getApellidos() {
		return apellidos;
	}

	/**
	 * @param apellidos the apellidos to set
	 */
	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	/**
	 * @return the direccion
	 */
	public String getDireccion() {
		return direccion;
	}

	/**
	 * @param direccion the direccion to set
	 */
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	/**
	 * @return the telefonoFijo
	 */
	public String getTelefonoFijo() {
		return telefonoFijo;
	}

	/**
	 * @param telefonoFijo the telefonoFijo to set
	 */
	public void setTelefonoFijo(String telefonoFijo) {
		this.telefonoFijo = telefonoFijo;
	}

	/**
	 * @return the telefonoCelular
	 */
	public String getTelefonoCelular() {
		return telefonoCelular;
	}

	/**
	 * @param telefonoCelular the telefonoCelular to set
	 */
	public void setTelefonoCelular(String telefonoCelular) {
		this.telefonoCelular = telefonoCelular;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return the numeroDocumento
	 */
	public String getNumeroDocumento() {
		return numeroDocumento;
	}

	/**
	 * @param numeroDocumento the numeroDocumento to set
	 */
	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	/**
	 * @return the mensajeError
	 */
	public String getMensajeError() {
		return mensajeError;
	}

	/**
	 * @param mensajeError the mensajeError to set
	 */
	public void setMensajeError(String mensajeError) {
		this.mensajeError = mensajeError;
	}

}
