package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbPreciosCancha generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbPreciosCancha implements java.io.Serializable {

	private int idtablaPrecios;
	private TbCanchasxunidadDeportiva tbCanchasxunidadDeportiva;
	private String descripcion;
	private Boolean lunes;
	private Boolean martes;
	private Boolean miercoles;
	private Boolean jueves;
	private Boolean viernes;
	private Boolean sabado;
	private Boolean domingo;
	private Date horaInicio;
	private Date horaFin;
	private Long valorHora;
	private Long descuento;

	public TbPreciosCancha() {
	}

	public TbPreciosCancha(int idtablaPrecios) {
		this.idtablaPrecios = idtablaPrecios;
	}

	public TbPreciosCancha(int idtablaPrecios, TbCanchasxunidadDeportiva tbCanchasxunidadDeportiva, String descripcion,
			Boolean lunes, Boolean martes, Boolean miercoles, Boolean jueves, Boolean viernes, Boolean sabado,
			Boolean domingo, Date horaInicio, Date horaFin, Long valorHora, Long descuento) {
		this.idtablaPrecios = idtablaPrecios;
		this.tbCanchasxunidadDeportiva = tbCanchasxunidadDeportiva;
		this.descripcion = descripcion;
		this.lunes = lunes;
		this.martes = martes;
		this.miercoles = miercoles;
		this.jueves = jueves;
		this.viernes = viernes;
		this.sabado = sabado;
		this.domingo = domingo;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.valorHora = valorHora;
		this.descuento = descuento;
	}

	public int getIdtablaPrecios() {
		return this.idtablaPrecios;
	}

	public void setIdtablaPrecios(int idtablaPrecios) {
		this.idtablaPrecios = idtablaPrecios;
	}

	public TbCanchasxunidadDeportiva getTbCanchasxunidadDeportiva() {
		return this.tbCanchasxunidadDeportiva;
	}

	public void setTbCanchasxunidadDeportiva(TbCanchasxunidadDeportiva tbCanchasxunidadDeportiva) {
		this.tbCanchasxunidadDeportiva = tbCanchasxunidadDeportiva;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getLunes() {
		return this.lunes;
	}

	public void setLunes(Boolean lunes) {
		this.lunes = lunes;
	}

	public Boolean getMartes() {
		return this.martes;
	}

	public void setMartes(Boolean martes) {
		this.martes = martes;
	}

	public Boolean getMiercoles() {
		return this.miercoles;
	}

	public void setMiercoles(Boolean miercoles) {
		this.miercoles = miercoles;
	}

	public Boolean getJueves() {
		return this.jueves;
	}

	public void setJueves(Boolean jueves) {
		this.jueves = jueves;
	}

	public Boolean getViernes() {
		return this.viernes;
	}

	public void setViernes(Boolean viernes) {
		this.viernes = viernes;
	}

	public Boolean getSabado() {
		return this.sabado;
	}

	public void setSabado(Boolean sabado) {
		this.sabado = sabado;
	}

	public Boolean getDomingo() {
		return this.domingo;
	}

	public void setDomingo(Boolean domingo) {
		this.domingo = domingo;
	}

	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	public Long getValorHora() {
		return this.valorHora;
	}

	public void setValorHora(Long valorHora) {
		this.valorHora = valorHora;
	}

	public Long getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Long descuento) {
		this.descuento = descuento;
	}

}
