package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbPreciosCancha generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbPreciosCancha implements java.io.Serializable {

	private int idtablaPrecios;
	private String descripcion;
	private Boolean lunes;
	private Boolean martes;
	private Boolean miercoles;
	private Boolean jueves;
	private Boolean viernes;
	private Boolean sabado;
	private Boolean domingo;
	private Date horaInicio;
	private Date horaFin;
	private Long valorHora;
	private Long descuento;
	private TbCanchas tbCanchas;

	/**
	 * Constructor
	 */
	public TbPreciosCancha() {
		super();
	}

	/**
	 * @return the idtablaPrecios
	 */
	public int getIdtablaPrecios() {
		return idtablaPrecios;
	}

	/**
	 * @param idtablaPrecios the idtablaPrecios to set
	 */
	public void setIdtablaPrecios(int idtablaPrecios) {
		this.idtablaPrecios = idtablaPrecios;
	}

	/**
	 * @return the descripcion
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * @param descripcion the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * @return the lunes
	 */
	public Boolean getLunes() {
		return lunes;
	}

	/**
	 * @param lunes the lunes to set
	 */
	public void setLunes(Boolean lunes) {
		this.lunes = lunes;
	}

	/**
	 * @return the martes
	 */
	public Boolean getMartes() {
		return martes;
	}

	/**
	 * @param martes the martes to set
	 */
	public void setMartes(Boolean martes) {
		this.martes = martes;
	}

	/**
	 * @return the miercoles
	 */
	public Boolean getMiercoles() {
		return miercoles;
	}

	/**
	 * @param miercoles the miercoles to set
	 */
	public void setMiercoles(Boolean miercoles) {
		this.miercoles = miercoles;
	}

	/**
	 * @return the jueves
	 */
	public Boolean getJueves() {
		return jueves;
	}

	/**
	 * @param jueves the jueves to set
	 */
	public void setJueves(Boolean jueves) {
		this.jueves = jueves;
	}

	/**
	 * @return the viernes
	 */
	public Boolean getViernes() {
		return viernes;
	}

	/**
	 * @param viernes the viernes to set
	 */
	public void setViernes(Boolean viernes) {
		this.viernes = viernes;
	}

	/**
	 * @return the sabado
	 */
	public Boolean getSabado() {
		return sabado;
	}

	/**
	 * @param sabado the sabado to set
	 */
	public void setSabado(Boolean sabado) {
		this.sabado = sabado;
	}

	/**
	 * @return the domingo
	 */
	public Boolean getDomingo() {
		return domingo;
	}

	/**
	 * @param domingo the domingo to set
	 */
	public void setDomingo(Boolean domingo) {
		this.domingo = domingo;
	}

	/**
	 * @return the horaInicio
	 */
	public Date getHoraInicio() {
		return horaInicio;
	}

	/**
	 * @param horaInicio the horaInicio to set
	 */
	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	/**
	 * @return the horaFin
	 */
	public Date getHoraFin() {
		return horaFin;
	}

	/**
	 * @param horaFin the horaFin to set
	 */
	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	/**
	 * @return the valorHora
	 */
	public Long getValorHora() {
		return valorHora;
	}

	/**
	 * @param valorHora the valorHora to set
	 */
	public void setValorHora(Long valorHora) {
		this.valorHora = valorHora;
	}

	/**
	 * @return the descuento
	 */
	public Long getDescuento() {
		return descuento;
	}

	/**
	 * @param descuento the descuento to set
	 */
	public void setDescuento(Long descuento) {
		this.descuento = descuento;
	}

	/**
	 * @return the tbCanchas
	 */
	public TbCanchas getTbCanchas() {
		return tbCanchas;
	}

	/**
	 * @param tbCanchas the tbCanchas to set
	 */
	public void setTbCanchas(TbCanchas tbCanchas) {
		this.tbCanchas = tbCanchas;
	}

}
