package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbReservas generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbReservas implements java.io.Serializable {

	private int idreserva;
	private TbCanchasxunidadDeportiva tbCanchasxunidadDeportiva;
	private Date fechaInicio;
	private Date fechaFin;
	private Integer usuario;
	private Integer tiempo;
	private BigDecimal valor;
	private Integer estado;

	public TbReservas() {
	}

	public TbReservas(int idreserva) {
		this.idreserva = idreserva;
	}

	public TbReservas(int idreserva, TbCanchasxunidadDeportiva tbCanchasxunidadDeportiva, Date fechaInicio,
			Date fechaFin, Integer usuario, Integer tiempo, BigDecimal valor, Integer estado) {
		this.idreserva = idreserva;
		this.tbCanchasxunidadDeportiva = tbCanchasxunidadDeportiva;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.usuario = usuario;
		this.tiempo = tiempo;
		this.valor = valor;
		this.estado = estado;
	}

	public int getIdreserva() {
		return this.idreserva;
	}

	public void setIdreserva(int idreserva) {
		this.idreserva = idreserva;
	}

	public TbCanchasxunidadDeportiva getTbCanchasxunidadDeportiva() {
		return this.tbCanchasxunidadDeportiva;
	}

	public void setTbCanchasxunidadDeportiva(TbCanchasxunidadDeportiva tbCanchasxunidadDeportiva) {
		this.tbCanchasxunidadDeportiva = tbCanchasxunidadDeportiva;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Integer getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Integer usuario) {
		this.usuario = usuario;
	}

	public Integer getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(Integer tiempo) {
		this.tiempo = tiempo;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}
}
