package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbRoles generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbRoles implements java.io.Serializable {

	private int idrol;
	private String nombre;

	public TbRoles() {
	}

	public TbRoles(int idrol) {
		this.idrol = idrol;
	}

	public TbRoles(int idrol, String nombre) {
		this.idrol = idrol;
		this.nombre = nombre;
	}

	public int getIdrol() {
		return this.idrol;
	}

	public void setIdrol(int idrol) {
		this.idrol = idrol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}
