package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbTipoEscenario generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbTipoEscenario implements java.io.Serializable {

	private int idtipoEscenario;
	private String descripcion;

	public TbTipoEscenario() {
	}

	public TbTipoEscenario(int idtipoEscenario) {
		this.idtipoEscenario = idtipoEscenario;
	}

	public TbTipoEscenario(int idtipoEscenario, String descripcion) {
		this.idtipoEscenario = idtipoEscenario;
		this.descripcion = descripcion;
	}

	public int getIdtipoEscenario() {
		return this.idtipoEscenario;
	}

	public void setIdtipoEscenario(int idtipoEscenario) {
		this.idtipoEscenario = idtipoEscenario;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}
