package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbTipoEscenario generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbTipoEscenario implements java.io.Serializable {

	private int idtipoEscenario;
	private String descripcion;

	private String mensajeError;
	
	/**
	 * Constructor
	 */
	public TbTipoEscenario() {
		super();
	}

	/**
	 * @param mensajeError
	 */
	public TbTipoEscenario(String mensajeError) {
		super();
		this.mensajeError = mensajeError;
	}

	public int getIdtipoEscenario() {
		return idtipoEscenario;
	}

	public void setIdtipoEscenario(int idtipoEscenario) {
		this.idtipoEscenario = idtipoEscenario;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getMensajeError() {
		return mensajeError;
	}

	public void setMensajeError(String mensajeError) {
		this.mensajeError = mensajeError;
	}
}
