package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbTipoEscenario generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbTipoEscenario implements java.io.Serializable {

	private int idtipoEscenario;
	private String descripcion;

	
	/**
	 * Constructor
	 */
	public TbTipoEscenario() {
		super();
	}

	/**
	 * @param idtipoEscenario
	 * @param descripcion
	 */
	public TbTipoEscenario(int idtipoEscenario, String descripcion) {
		super();
		this.idtipoEscenario = idtipoEscenario;
		this.descripcion = descripcion;
	}

	/**
	 * @return the idtipoEscenario
	 */
	public int getIdtipoEscenario() {
		return idtipoEscenario;
	}

	/**
	 * @param idtipoEscenario the idtipoEscenario to set
	 */
	public void setIdtipoEscenario(int idtipoEscenario) {
		this.idtipoEscenario = idtipoEscenario;
	}

	/**
	 * @return the descripcion
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * @param descripcion the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
