package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbTiposDocumento generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbTiposDocumento implements java.io.Serializable {

	private int idtipoDocumento;
	private String descripcion;
	private String abreviado;
	
	private String mensajeError;

	/**
	 * 
	 */
	public TbTiposDocumento() {
		super();
	}
	

	/**
	 * @param mensajeError
	 */
	public TbTiposDocumento(String mensajeError) {
		super();
		this.mensajeError = mensajeError;
	}



	/**
	 * @return the idtipoDocumento
	 */
	public int getIdtipoDocumento() {
		return idtipoDocumento;
	}

	/**
	 * @param idtipoDocumento the idtipoDocumento to set
	 */
	public void setIdtipoDocumento(int idtipoDocumento) {
		this.idtipoDocumento = idtipoDocumento;
	}

	/**
	 * @return the descripcion
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * @param descripcion the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * @return the abreviado
	 */
	public String getAbreviado() {
		return abreviado;
	}

	/**
	 * @param abreviado the abreviado to set
	 */
	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	/**
	 * @return the mensajeError
	 */
	public String getMensajeError() {
		return mensajeError;
	}

	/**
	 * @param mensajeError the mensajeError to set
	 */
	public void setMensajeError(String mensajeError) {
		this.mensajeError = mensajeError;
	}

}
