package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbTiposDeporte generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbTiposDeporte implements java.io.Serializable {

	private int idtipoDeporte;
	private String nombre;

	public TbTiposDeporte() {
	}

	public TbTiposDeporte(int idtipoDeporte) {
		this.idtipoDeporte = idtipoDeporte;
	}

	public TbTiposDeporte(int idtipoDeporte, String nombre) {
		this.idtipoDeporte = idtipoDeporte;
		this.nombre = nombre;
	}

	public int getIdtipoDeporte() {
		return this.idtipoDeporte;
	}

	public void setIdtipoDeporte(int idtipoDeporte) {
		this.idtipoDeporte = idtipoDeporte;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}
