package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbUsuarios generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbUsuarios implements java.io.Serializable {

	private int idusuario;
	private TbEstados tbEstados;
	private TbPersonas tbPersonas;
	private TbRoles tbRoles;
	private String login;
	private String password;

	public TbUsuarios() {
	}

	public TbUsuarios(int idusuario) {
		this.idusuario = idusuario;
	}

	public TbUsuarios(int idusuario, TbEstados tbEstados, TbPersonas tbPersonas, TbRoles tbRoles, String login,
			String password) {
		this.idusuario = idusuario;
		this.tbEstados = tbEstados;
		this.tbPersonas = tbPersonas;
		this.tbRoles = tbRoles;
		this.login = login;
		this.password = password;
	}

	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	public TbEstados getTbEstados() {
		return this.tbEstados;
	}

	public void setTbEstados(TbEstados tbEstados) {
		this.tbEstados = tbEstados;
	}

	public TbPersonas getTbPersonas() {
		return this.tbPersonas;
	}

	public void setTbPersonas(TbPersonas tbPersonas) {
		this.tbPersonas = tbPersonas;
	}

	public TbRoles getTbRoles() {
		return this.tbRoles;
	}

	public void setTbRoles(TbRoles tbRoles) {
		this.tbRoles = tbRoles;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
