package com.tododeportes.backend.dto;
// Generated 26/03/2016 03:44:35 PM by Hibernate Tools 4.3.1.Final

/**
 * TbUsuarios generated by hbm2java
 */
@SuppressWarnings("serial")
public class TbUsuarios implements java.io.Serializable {

	private int idusuario;
	private TbEstados tbEstados;
	private TbPersonas tbPersonas;
	private TbRoles tbRoles;
	private String login;
	private String password;

	

	/**
	 * Constructor 
	 */
	public TbUsuarios() {
		super();
	}
	

	/**
	 * @param idusuario
	 * @param tbEstados
	 * @param tbPersonas
	 * @param tbRoles
	 * @param login
	 * @param password
	 */
	public TbUsuarios(int idusuario, TbEstados tbEstados, TbPersonas tbPersonas, TbRoles tbRoles, String login,
			String password) {
		super();
		this.idusuario = idusuario;
		this.tbEstados = tbEstados;
		this.tbPersonas = tbPersonas;
		this.tbRoles = tbRoles;
		this.login = login;
		this.password = password;
	}



	/**
	 * @return the idusuario
	 */
	public int getIdusuario() {
		return idusuario;
	}

	/**
	 * @param idusuario the idusuario to set
	 */
	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	/**
	 * @return the tbEstados
	 */
	public TbEstados getTbEstados() {
		return tbEstados;
	}

	/**
	 * @param tbEstados the tbEstados to set
	 */
	public void setTbEstados(TbEstados tbEstados) {
		this.tbEstados = tbEstados;
	}

	/**
	 * @return the tbPersonas
	 */
	public TbPersonas getTbPersonas() {
		return tbPersonas;
	}

	/**
	 * @param tbPersonas the tbPersonas to set
	 */
	public void setTbPersonas(TbPersonas tbPersonas) {
		this.tbPersonas = tbPersonas;
	}

	/**
	 * @return the tbRoles
	 */
	public TbRoles getTbRoles() {
		return tbRoles;
	}

	/**
	 * @param tbRoles the tbRoles to set
	 */
	public void setTbRoles(TbRoles tbRoles) {
		this.tbRoles = tbRoles;
	}

	/**
	 * @return the login
	 */
	public String getLogin() {
		return login;
	}

	/**
	 * @param login the login to set
	 */
	public void setLogin(String login) {
		this.login = login;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}
